version: '3.8'

services:
  gau-authorization-service:
    image: iamqbao/gau_authorization_service:latest
    container_name: gau-authorization-service
    restart: always
    env_file:
      - .env
    environment:
      - PGPOOL_URL=${PGPOOL_URL}
    networks:
      - app-network

  redis-authorization-service:
    image: redis:7.2-alpine
    container_name: redis-authorization-service
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_ADDRESS=redis://redis-authorization-service:6379
      - REDIS_DB=0
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  pgpool:
    image: bitnami/pgpool:latest
    container_name: pgpool
    restart: always
    env_file:
      - .env
    environment:
      - PGPOOL_BACKEND_NODES=0:postgres:5432
      - PGPOOL_POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - PGPOOL_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPOOL_SR_CHECK_USER=${POSTGRES_USERNAME}
      - PGPOOL_SR_CHECK_PASSWORD=${POSTGRES_PASSWORD}
      - PGPOOL_HEALTH_CHECK_USER=${POSTGRES_USERNAME}
      - PGPOOL_HEALTH_CHECK_PASSWORD=${POSTGRES_PASSWORD}
      - PGPOOL_ADMIN_USERNAME=${PGPOOL_ADMIN_USERNAME}
      - PGPOOL_ADMIN_PASSWORD=${PGPOOL_ADMIN_PASSWORD}
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_LOG_CONNECTIONS=yes
      - PGPOOL_ENABLE_LOG_HOSTNAME=yes
    ports:
      - "5433:5432"
    networks:
      - app-network
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    env_file:
      - .env
    command: sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  postgres-data:
  redis-data:

networks:
  app-network:
    external: true