apiVersion: v1
kind: ConfigMap
metadata:
  name: bao-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
data:
  PGPOOL_HOST: "${PGPOOL_HOST}"
  PGPOOL_DB: "${PGPOOL_DB}"
  PGPOOL_USER: "${PGPOOL_USER}"
  PGPOOL_PORT: "${PGPOOL_PORT}"
  PGPOOL_URL: "${PGPOOL_URL}"
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  JWT_ALGORITHM: "${JWT_ALGORITHM}"
  JWT_EXPIRE: "${JWT_EXPIRE}"
  ALLOWED_DOMAINS: "${ALLOWED_DOMAINS}"
  GLOBAL_DOMAIN: "${GLOBAL_DOMAIN}"
  REDIS_ADDRESS: "${REDIS_ADDRESS}"
  REDIS_DB: "${REDIS_DB}"